module.exports = {
  countriesList: [
    { name_ar: "", name_fr: "Afghanistan", code: "AF" },
    { name_ar: "", name_fr: "Åland Islands", code: "AX" },
    { name_ar: "", name_fr: "Albania", code: "AL" },
    { name_ar: "", name_fr: "Algeria", code: "DZ" },
    { name_ar: "", name_fr: "American Samoa", code: "AS" },
    { name_ar: "", name_fr: "AndorrA", code: "AD" },
    { name_ar: "", name_fr: "Angola", code: "AO" },
    { name_ar: "", name_fr: "Anguilla", code: "AI" },
    { name_ar: "", name_fr: "Antarctica", code: "AQ" },
    { name_ar: "", name_fr: "Antigua and Barbuda", code: "AG" },
    { name_ar: "", name_fr: "Argentina", code: "AR" },
    { name_ar: "", name_fr: "Armenia", code: "AM" },
    { name_ar: "", name_fr: "Aruba", code: "AW" },
    { name_ar: "", name_fr: "Australia", code: "AU" },
    { name_ar: "", name_fr: "Austria", code: "AT" },
    { name_ar: "", name_fr: "Azerbaijan", code: "AZ" },
    { name_ar: "", name_fr: "Bahamas", code: "BS" },
    { name_ar: "", name_fr: "Bahrain", code: "BH" },
    { name_ar: "", name_fr: "Bangladesh", code: "BD" },
    { name_ar: "", name_fr: "Barbados", code: "BB" },
    { name_ar: "", name_fr: "Belarus", code: "BY" },
    { name_ar: "", name_fr: "Belgium", code: "BE" },
    { name_ar: "", name_fr: "Belize", code: "BZ" },
    { name_ar: "", name_fr: "Benin", code: "BJ" },
    { name_ar: "", name_fr: "Bermuda", code: "BM" },
    { name_ar: "", name_fr: "Bhutan", code: "BT" },
    { name_ar: "", name_fr: "Bolivia", code: "BO" },
    { name_ar: "", name_fr: "Bosnia and Herzegovina", code: "BA" },
    { name_ar: "", name_fr: "Botswana", code: "BW" },
    { name_ar: "", name_fr: "Bouvet Island", code: "BV" },
    { name_ar: "", name_fr: "Brazil", code: "BR" },
    { name_ar: "", name_fr: "British Indian Ocean Territory", code: "IO" },
    { name_ar: "", name_fr: "Brunei Darussalam", code: "BN" },
    { name_ar: "", name_fr: "Bulgaria", code: "BG" },
    { name_ar: "", name_fr: "Burkina Faso", code: "BF" },
    { name_ar: "", name_fr: "Burundi", code: "BI" },
    { name_ar: "", name_fr: "Cambodia", code: "KH" },
    { name_ar: "", name_fr: "Cameroon", code: "CM" },
    { name_ar: "", name_fr: "Canada", code: "CA" },
    { name_ar: "", name_fr: "Cape Verde", code: "CV" },
    { name_ar: "", name_fr: "Cayman Islands", code: "KY" },
    { name_ar: "", name_fr: "Central African Republic", code: "CF" },
    { name_ar: "", name_fr: "Chad", code: "TD" },
    { name_ar: "", name_fr: "Chile", code: "CL" },
    { name_ar: "", name_fr: "China", code: "CN" },
    { name_ar: "", name_fr: "Christmas Island", code: "CX" },
    { name_ar: "", name_fr: "Cocos (Keeling) Islands", code: "CC" },
    { name_ar: "", name_fr: "Colombia", code: "CO" },
    { name_ar: "", name_fr: "Comoros", code: "KM" },
    { name_ar: "", name_fr: "Congo", code: "CG" },
    {
      name_ar: "",
      name_fr: "Congo, The Democratic Republic of the",
      code: "CD",
    },
    { name_ar: "", name_fr: "Cook Islands", code: "CK" },
    { name_ar: "", name_fr: "Costa Rica", code: "CR" },
    { name_ar: "", name_fr: 'Cote D"Ivoire', code: "CI" },
    { name_ar: "", name_fr: "Croatia", code: "HR" },
    { name_ar: "", name_fr: "Cuba", code: "CU" },
    { name_ar: "", name_fr: "Cyprus", code: "CY" },
    { name_ar: "", name_fr: "Czech Republic", code: "CZ" },
    { name_ar: "", name_fr: "Denmark", code: "DK" },
    { name_ar: "", name_fr: "Djibouti", code: "DJ" },
    { name_ar: "", name_fr: "Dominica", code: "DM" },
    { name_ar: "", name_fr: "Dominican Republic", code: "DO" },
    { name_ar: "", name_fr: "Ecuador", code: "EC" },
    { name_ar: "", name_fr: "Egypt", code: "EG" },
    { name_ar: "", name_fr: "El Salvador", code: "SV" },
    { name_ar: "", name_fr: "Equatorial Guinea", code: "GQ" },
    { name_ar: "", name_fr: "Eritrea", code: "ER" },
    { name_ar: "", name_fr: "Estonia", code: "EE" },
    { name_ar: "", name_fr: "Ethiopia", code: "ET" },
    { name_ar: "", name_fr: "Falkland Islands (Malvinas)", code: "FK" },
    { name_ar: "", name_fr: "Faroe Islands", code: "FO" },
    { name_ar: "", name_fr: "Fiji", code: "FJ" },
    { name_ar: "", name_fr: "Finland", code: "FI" },
    { name_ar: "", name_fr: "France", code: "FR" },
    { name_ar: "", name_fr: "French Guiana", code: "GF" },
    { name_ar: "", name_fr: "French Polynesia", code: "PF" },
    { name_ar: "", name_fr: "French Southern Territories", code: "TF" },
    { name_ar: "", name_fr: "Gabon", code: "GA" },
    { name_ar: "", name_fr: "Gambia", code: "GM" },
    { name_ar: "", name_fr: "Georgia", code: "GE" },
    { name_ar: "", name_fr: "Germany", code: "DE" },
    { name_ar: "", name_fr: "Ghana", code: "GH" },
    { name_ar: "", name_fr: "Gibraltar", code: "GI" },
    { name_ar: "", name_fr: "Greece", code: "GR" },
    { name_ar: "", name_fr: "Greenland", code: "GL" },
    { name_ar: "", name_fr: "Grenada", code: "GD" },
    { name_ar: "", name_fr: "Guadeloupe", code: "GP" },
    { name_ar: "", name_fr: "Guam", code: "GU" },
    { name_ar: "", name_fr: "Guatemala", code: "GT" },
    { name_ar: "", name_fr: "Guernsey", code: "GG" },
    { name_ar: "", name_fr: "Guinea", code: "GN" },
    { name_ar: "", name_fr: "Guinea-Bissau", code: "GW" },
    { name_ar: "", name_fr: "Guyana", code: "GY" },
    { name_ar: "", name_fr: "Haiti", code: "HT" },
    { name_ar: "", name_fr: "Heard Island and Mcdonald Islands", code: "HM" },
    { name_ar: "", name_fr: "Holy See (Vatican City State)", code: "VA" },
    { name_ar: "", name_fr: "Honduras", code: "HN" },
    { name_ar: "", name_fr: "Hong Kong", code: "HK" },
    { name_ar: "", name_fr: "Hungary", code: "HU" },
    { name_ar: "", name_fr: "Iceland", code: "IS" },
    { name_ar: "", name_fr: "India", code: "IN" },
    { name_ar: "", name_fr: "Indonesia", code: "ID" },
    { name_ar: "", name_fr: "Iran, Islamic Republic Of", code: "IR" },
    { name_ar: "", name_fr: "Iraq", code: "IQ" },
    { name_ar: "", name_fr: "Ireland", code: "IE" },
    { name_ar: "", name_fr: "Isle of Man", code: "IM" },
    { name_ar: "", name_fr: "Israel", code: "IL" },
    { name_ar: "", name_fr: "Italy", code: "IT" },
    { name_ar: "", name_fr: "Jamaica", code: "JM" },
    { name_ar: "", name_fr: "Japan", code: "JP" },
    { name_ar: "", name_fr: "Jersey", code: "JE" },
    { name_ar: "", name_fr: "Jordan", code: "JO" },
    { name_ar: "", name_fr: "Kazakhstan", code: "KZ" },
    { name_ar: "", name_fr: "Kenya", code: "KE" },
    { name_ar: "", name_fr: "Kiribati", code: "KI" },
    {
      name_ar: "",
      name_fr: "Korea, Democratic People'S Republic of",
      code: "KP",
    },
    { name_ar: "", name_fr: "Korea, Republic of", code: "KR" },
    { name_ar: "", name_fr: "Kuwait", code: "KW" },
    { name_ar: "", name_fr: "Kyrgyzstan", code: "KG" },
    { name_ar: "", name_fr: "Lao People'S Democratic Republic", code: "LA" },
    { name_ar: "", name_fr: "Latvia", code: "LV" },
    { name_ar: "", name_fr: "Lebanon", code: "LB" },
    { name_ar: "", name_fr: "Lesotho", code: "LS" },
    { name_ar: "", name_fr: "Liberia", code: "LR" },
    { name_ar: "", name_fr: "Libyan Arab Jamahiriya", code: "LY" },
    { name_ar: "", name_fr: "Liechtenstein", code: "LI" },
    { name_ar: "", name_fr: "Lithuania", code: "LT" },
    { name_ar: "", name_fr: "Luxembourg", code: "LU" },
    { name_ar: "", name_fr: "Macao", code: "MO" },
    {
      name_ar: "",
      name_fr: "Macedonia, The Former Yugoslav Republic of",
      code: "MK",
    },
    { name_ar: "", name_fr: "Madagascar", code: "MG" },
    { name_ar: "", name_fr: "Malawi", code: "MW" },
    { name_ar: "", name_fr: "Malaysia", code: "MY" },
    { name_ar: "", name_fr: "Maldives", code: "MV" },
    { name_ar: "", name_fr: "Mali", code: "ML" },
    { name_ar: "", name_fr: "Malta", code: "MT" },
    { name_ar: "", name_fr: "Marshall Islands", code: "MH" },
    { name_ar: "", name_fr: "Martinique", code: "MQ" },
    { name_ar: "", name_fr: "Mauritania", code: "MR" },
    { name_ar: "", name_fr: "Mauritius", code: "MU" },
    { name_ar: "", name_fr: "Mayotte", code: "YT" },
    { name_ar: "", name_fr: "Mexico", code: "MX" },
    { name_ar: "", name_fr: "Micronesia, Federated States of", code: "FM" },
    { name_ar: "", name_fr: "Moldova, Republic of", code: "MD" },
    { name_ar: "", name_fr: "Monaco", code: "MC" },
    { name_ar: "", name_fr: "Mongolia", code: "MN" },
    { name_ar: "", name_fr: "Montserrat", code: "MS" },
    { name_ar: "", name_fr: "Morocco", code: "MA" },
    { name_ar: "", name_fr: "Mozambique", code: "MZ" },
    { name_ar: "", name_fr: "Myanmar", code: "MM" },
    { name_ar: "", name_fr: "Namibia", code: "NA" },
    { name_ar: "", name_fr: "Nauru", code: "NR" },
    { name_ar: "", name_fr: "Nepal", code: "NP" },
    { name_ar: "", name_fr: "Netherlands", code: "NL" },
    { name_ar: "", name_fr: "Netherlands Antilles", code: "AN" },
    { name_ar: "", name_fr: "New Caledonia", code: "NC" },
    { name_ar: "", name_fr: "New Zealand", code: "NZ" },
    { name_ar: "", name_fr: "Nicaragua", code: "NI" },
    { name_ar: "", name_fr: "Niger", code: "NE" },
    { name_ar: "", name_fr: "Nigeria", code: "NG" },
    { name_ar: "", name_fr: "Niue", code: "NU" },
    { name_ar: "", name_fr: "Norfolk Island", code: "NF" },
    { name_ar: "", name_fr: "Northern Mariana Islands", code: "MP" },
    { name_ar: "", name_fr: "Norway", code: "NO" },
    { name_ar: "", name_fr: "Oman", code: "OM" },
    { name_ar: "", name_fr: "Pakistan", code: "PK" },
    { name_ar: "", name_fr: "Palau", code: "PW" },
    { name_ar: "", name_fr: "Palestinian Territory, Occupied", code: "PS" },
    { name_ar: "", name_fr: "Panama", code: "PA" },
    { name_ar: "", name_fr: "Papua New Guinea", code: "PG" },
    { name_ar: "", name_fr: "Paraguay", code: "PY" },
    { name_ar: "", name_fr: "Peru", code: "PE" },
    { name_ar: "", name_fr: "Philippines", code: "PH" },
    { name_ar: "", name_fr: "Pitcairn", code: "PN" },
    { name_ar: "", name_fr: "Poland", code: "PL" },
    { name_ar: "", name_fr: "Portugal", code: "PT" },
    { name_ar: "", name_fr: "Puerto Rico", code: "PR" },
    { name_ar: "", name_fr: "Qatar", code: "QA" },
    { name_ar: "", name_fr: "Reunion", code: "RE" },
    { name_ar: "", name_fr: "Romania", code: "RO" },
    { name_ar: "", name_fr: "Russian Federation", code: "RU" },
    { name_ar: "", name_fr: "RWANDA", code: "RW" },
    { name_ar: "", name_fr: "Saint Helena", code: "SH" },
    { name_ar: "", name_fr: "Saint Kitts and Nevis", code: "KN" },
    { name_ar: "", name_fr: "Saint Lucia", code: "LC" },
    { name_ar: "", name_fr: "Saint Pierre and Miquelon", code: "PM" },
    { name_ar: "", name_fr: "Saint Vincent and the Grenadines", code: "VC" },
    { name_ar: "", name_fr: "Samoa", code: "WS" },
    { name_ar: "", name_fr: "San Marino", code: "SM" },
    { name_ar: "", name_fr: "Sao Tome and Principe", code: "ST" },
    { name_ar: "", name_fr: "Saudi Arabia", code: "SA" },
    { name_ar: "", name_fr: "Senegal", code: "SN" },
    { name_ar: "", name_fr: "Serbia and Montenegro", code: "CS" },
    { name_ar: "", name_fr: "Seychelles", code: "SC" },
    { name_ar: "", name_fr: "Sierra Leone", code: "SL" },
    { name_ar: "", name_fr: "Singapore", code: "SG" },
    { name_ar: "", name_fr: "Slovakia", code: "SK" },
    { name_ar: "", name_fr: "Slovenia", code: "SI" },
    { name_ar: "", name_fr: "Solomon Islands", code: "SB" },
    { name_ar: "", name_fr: "Somalia", code: "SO" },
    { name_ar: "", name_fr: "South Africa", code: "ZA" },
    {
      name_ar: "",
      name_fr: "South Georgia and the South Sandwich Islands",
      code: "GS",
    },
    { name_ar: "", name_fr: "Spain", code: "ES" },
    { name_ar: "", name_fr: "Sri Lanka", code: "LK" },
    { name_ar: "", name_fr: "Sudan", code: "SD" },
    { name_ar: "", name_fr: "Svalbard and Jan Mayen", code: "SJ" },
    { name_ar: "", name_fr: "Swaziland", code: "SZ" },
    { name_ar: "", name_fr: "Sweden", code: "SE" },
    { name_ar: "", name_fr: "Switzerland", code: "CH" },
    { name_ar: "", name_fr: "Syrian Arab Republic", code: "SY" },
    { name_ar: "", name_fr: "Taiwan, Province of China", code: "TW" },
    { name_ar: "", name_fr: "Tajikistan", code: "TJ" },
    { name_ar: "", name_fr: "Tanzania, United Republic of", code: "TZ" },
    { name_ar: "", name_fr: "Thailand", code: "TH" },
    { name_ar: "", name_fr: "Timor-Leste", code: "TL" },
    { name_ar: "", name_fr: "Togo", code: "TG" },
    { name_ar: "", name_fr: "Tokelau", code: "TK" },
    { name_ar: "", name_fr: "Tonga", code: "TO" },
    { name_ar: "", name_fr: "Trinidad and Tobago", code: "TT" },
    { name_ar: "", name_fr: "Tunisia", code: "TN" },
    { name_ar: "", name_fr: "Turkey", code: "TR" },
    { name_ar: "", name_fr: "Turkmenistan", code: "TM" },
    { name_ar: "", name_fr: "Turks and Caicos Islands", code: "TC" },
    { name_ar: "", name_fr: "Tuvalu", code: "TV" },
    { name_ar: "", name_fr: "Uganda", code: "UG" },
    { name_ar: "", name_fr: "Ukraine", code: "UA" },
    { name_ar: "", name_fr: "United Arab Emirates", code: "AE" },
    { name_ar: "", name_fr: "United Kingdom", code: "GB" },
    { name_ar: "", name_fr: "United States", code: "US" },
    {
      name_ar: "",
      name_fr: "United States Minor Outlying Islands",
      code: "UM",
    },
    { name_ar: "", name_fr: "Uruguay", code: "UY" },
    { name_ar: "", name_fr: "Uzbekistan", code: "UZ" },
    { name_ar: "", name_fr: "Vanuatu", code: "VU" },
    { name_ar: "", name_fr: "Venezuela", code: "VE" },
    { name_ar: "", name_fr: "Viet Nam", code: "VN" },
    { name_ar: "", name_fr: "Virgin Islands, British", code: "VG" },
    { name_ar: "", name_fr: "Virgin Islands, U.S.", code: "VI" },
    { name_ar: "", name_fr: "Wallis and Futuna", code: "WF" },
    { name_ar: "", name_fr: "Western Sahara", code: "EH" },
    { name_ar: "", name_fr: "Yemen", code: "YE" },
    { name_ar: "", name_fr: "Zambia", code: "ZM" },
    { name_ar: "", name_fr: "Zimbabwe", code: "ZW" },
  ],
};
